// src/domains/resourceManage/api/resourceManageApi.mock.ts

import type {
  Resource,
  ResourceStatus,
  EquipmentType,
  PositionType,
  Datacenter,
  Rack,
} from "../types/resource.types";

// --- Datacenter 목 데이터 ---
export const MOCK_DATACENTERS: Datacenter[] = [
  {
    id: "dc1",
    name: "서울 데이터센터",
    code: "DC-SEL-001",
    location: "서울시 강남구",
    status: "ACTIVE",
    rackCount: 50,
    managerName: "김철수",
  },
  {
    id: "dc2",
    name: "부산 데이터센터",
    code: "DC-BUS-001",
    location: "부산시 해운대구",
    status: "ACTIVE",
    rackCount: 30,
    managerName: "이영희",
  },
];

// --- Rack 목 데이터 ---
export const MOCK_RACKS: Rack[] = [
  {
    id: "rack1",
    rackName: "RACK-A01",
    groupNumber: "A-Zone",
    rackLocation: "Row 1 Col 1",
    totalUnits: 42,
    usedUnits: 30,
    availableUnits: 12,
    status: "ACTIVE",
    usageRate: 71.43,
    powerUsageRate: 65.5,
    currentPowerUsage: 3275.0,
    maxPowerCapacity: 5000.0,
    department: "IT팀",
    managerId: "1",
    datacenterId: "dc1", // MSW 필터링을 위한 편의용 필드
  },
  {
    id: "rack2",
    rackName: "RACK-A02",
    groupNumber: "A-Zone",
    rackLocation: "Row 1 Col 2",
    totalUnits: 48,
    usedUnits: 20,
    availableUnits: 28,
    status: "ACTIVE",
    usageRate: 41.67,
    powerUsageRate: 50.0,
    currentPowerUsage: 2500.0,
    maxPowerCapacity: 5000.0,
    department: "IT팀",
    managerId: "1",
    datacenterId: "dc1",
  },
  {
    id: "rack3",
    rackName: "RACK-B01",
    groupNumber: "B-Zone",
    rackLocation: "Row 1 Col 1",
    totalUnits: 42,
    usedUnits: 40,
    availableUnits: 2,
    status: "ACTIVE",
    usageRate: 95.24,
    powerUsageRate: 85.0,
    currentPowerUsage: 4250.0,
    maxPowerCapacity: 5000.0,
    department: "운영팀",
    managerId: "2",
    datacenterId: "dc2",
  },
];

// --- Resource (Equipment) 목 데이터 ---
export let MOCK_DATA: Resource[] = [
  // --- 1. Dell Server (NORMAL, dc1/rack1) ---
  {
    id: "1",
    equipmentName: "DB-Server-01",
    status: "NORMAL",
    ipAddress: "192.168.1.101",
    modelName: "Dell PowerEdge R740",
    location: "DC-SEL / RACK-A01 / 22U",
    manufacturer: "Dell",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: "dc1",
    rackId: "rack1",
    startUnit: 22,
    positionType: "FRONT",
    serialNumber: "DELL-SN-1001",
    os: "CentOS 7.9",
    cpuSpec: "Intel Xeon Silver 4210 @ 2.2GHz 2CPU",
    memorySpec: "128GB (8x 16GB) DDR4",
    diskSpec: "2TB NVMe SSD x 2, 4TB SAS HDD x 4",
    macAddress: "00:1A:2B:3C:4D:01",
    managerId: "admin_kim",
    installationDate: "2023-01-10",
    notes: "Main DB server for production.",
    monitoringEnabled: true,
    cpuThresholdWarning: 80,
    cpuThresholdCritical: 95,
    memoryThresholdWarning: 80,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 70,
    diskThresholdCritical: 90,
    imageUrlFront: "https://i.imgur.com/gA2ANEV.png", // 예시 이미지
    imageUrlRear: "https://i.imgur.com/v4o6nVL.png", // 예시 이미지
  },
  // --- 2. HP Server (MAINTENANCE, dc1/rack2) ---
  {
    id: "2",
    equipmentName: "Web-Server-02",
    status: "MAINTENANCE",
    ipAddress: "192.168.1.102",
    modelName: "HP ProLiant DL380 Gen10",
    location: "DC-SEL / RACK-A02 / 15U",
    manufacturer: "HP",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 15,
    positionType: "FRONT",
    serialNumber: "HP-SN-2002",
    os: "Ubuntu 22.04 LTS",
    cpuSpec: "AMD EPYC 7402P 24-Core",
    memorySpec: "256GB (8x 32GB) DDR4",
    diskSpec: "1TB NVMe SSD x 4",
    macAddress: "00:1A:2B:3C:4D:02",
    managerId: "admin_lee",
    installationDate: "2023-03-15",
    notes: "Web server cluster node 2. Scheduled maintenance.",
    monitoringEnabled: true,
    cpuThresholdWarning: 75,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 75,
    memoryThresholdCritical: 90,
    diskThresholdWarning: 80,
    diskThresholdCritical: 95,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 3. Cisco Switch (NORMAL, dc2/rack3) ---
  {
    id: "3",
    equipmentName: "Switch-Core-01",
    status: "NORMAL",
    ipAddress: "10.0.1.1",
    modelName: "Cisco Catalyst 9300",
    location: "DC-BUS / RACK-B01 / 42U",
    manufacturer: "Cisco",
    equipmentType: "SWITCH",
    unitSize: 1,
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 42,
    positionType: "FRONT",
    serialNumber: "CSCO-SN-3003",
    os: "IOS-XE",
    cpuSpec: "N/A",
    memorySpec: "8GB",
    diskSpec: "16GB Flash",
    macAddress: "00:1A:2B:3C:4D:03",
    managerId: "net_admin",
    installationDate: "2022-11-20",
    notes: "Busan DC Core Switch (Top of Rack)",
    monitoringEnabled: true,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: null, // 모니터링 안 함
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 4. NetApp Storage (INACTIVE, Unassigned) ---
  {
    id: "4",
    equipmentName: "Storage-Array-01",
    status: "INACTIVE",
    ipAddress: null, // 미할당
    modelName: "NetApp FAS8200",
    location: "미지정 (재고)",
    manufacturer: "NetApp",
    equipmentType: "SERVER", // (스토리지지만 타입은 SERVER로 예시)
    unitSize: 4,
    datacenterId: null,
    rackId: null,
    startUnit: null,
    positionType: null,
    serialNumber: "NTAP-SN-4004",
    os: "ONTAP 9",
    cpuSpec: "Intel Xeon",
    memorySpec: "128GB",
    diskSpec: "10TB SAS x 12",
    macAddress: null,
    managerId: "sys_admin",
    installationDate: null,
    notes: "Stock, awaiting deployment.",
    monitoringEnabled: false,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: 70,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 5. Cisco Router (NORMAL, dc1/rack1) ---
  {
    id: "5",
    equipmentName: "Router-Edge-01",
    status: "NORMAL",
    ipAddress: "192.168.1.1",
    modelName: "Cisco ASR 1001-X",
    location: "DC-SEL / RACK-A01 / 40U",
    manufacturer: "Cisco",
    equipmentType: "ROUTER",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack1",
    startUnit: 40,
    positionType: "FRONT",
    serialNumber: "CSCO-SN-5005",
    os: "IOS-XE",
    cpuSpec: "N/A",
    memorySpec: "8GB",
    diskSpec: "8GB Flash",
    macAddress: "00:1A:2B:3C:4D:05",
    managerId: "net_admin",
    installationDate: "2023-01-05",
    notes: "Seoul DC Edge Router.",
    monitoringEnabled: true,
    cpuThresholdWarning: 60,
    cpuThresholdCritical: 80,
    memoryThresholdWarning: 60,
    memoryThresholdCritical: 80,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 6. APC PDU (NORMAL, dc1/rack1) ---
  {
    id: "6",
    equipmentName: "PDU-A01-L",
    status: "NORMAL",
    ipAddress: "192.168.1.250",
    modelName: "APC AP8853",
    location: "DC-SEL / RACK-A01 / 1U", // (PDU는 0U일 수 있으나 예시로 1U)
    manufacturer: "APC",
    equipmentType: "PDU",
    unitSize: 1, // (0U PDU도 있지만, 폼 검증을 위해 1U로 가정)
    datacenterId: "dc1",
    rackId: "rack1",
    startUnit: 1, // (랙 하단)
    positionType: "REAR", // (PDU는 보통 후면)
    serialNumber: "APC-SN-6006",
    os: null,
    cpuSpec: null,
    memorySpec: null,
    diskSpec: null,
    macAddress: "00:1A:2B:3C:4D:06",
    managerId: "infra_team",
    installationDate: "2023-01-05",
    notes: "Rack A01 Left PDU.",
    monitoringEnabled: false, // (PDU는 모니터링 안 함 예시)
    cpuThresholdWarning: null,
    cpuThresholdCritical: null,
    memoryThresholdWarning: null,
    memoryThresholdCritical: null,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 7. Eaton UPS (NORMAL, dc1/rack2) ---
  {
    id: "7",
    equipmentName: "UPS-A-Zone",
    status: "NORMAL",
    ipAddress: "192.168.1.254",
    modelName: "Eaton 9PX",
    location: "DC-SEL / RACK-A02 / 1U",
    manufacturer: "Eaton",
    equipmentType: "UPS",
    unitSize: 2,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 1,
    positionType: "FRONT",
    serialNumber: "EATN-SN-7007",
    os: null,
    cpuSpec: null,
    memorySpec: null,
    diskSpec: null,
    macAddress: "00:1A:2B:3C:4D:07",
    managerId: "infra_team",
    installationDate: "2023-01-05",
    notes: "A-Zone UPS.",
    monitoringEnabled: false,
    cpuThresholdWarning: null,
    cpuThresholdCritical: null,
    memoryThresholdWarning: null,
    memoryThresholdCritical: null,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 8. Juniper Switch (NORMAL, dc2/rack3) ---
  {
    id: "8",
    equipmentName: "Switch-Access-B01",
    status: "NORMAL",
    ipAddress: "10.0.1.2",
    modelName: "Juniper EX4300",
    location: "DC-BUS / RACK-B01 / 41U",
    manufacturer: "Juniper",
    equipmentType: "SWITCH",
    unitSize: 1,
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 41,
    positionType: "FRONT",
    serialNumber: "JNPR-SN-8008",
    os: "Junos",
    cpuSpec: "N/A",
    memorySpec: "4GB",
    diskSpec: "8GB Flash",
    macAddress: "00:1A:2B:3C:4D:08",
    managerId: "net_admin",
    installationDate: "2022-11-20",
    notes: "Busan DC Access Switch.",
    monitoringEnabled: true,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 9. Lenovo Server (NORMAL, dc1/rack2) ---
  {
    id: "9",
    equipmentName: "K8S-Worker-01",
    status: "NORMAL",
    ipAddress: "192.168.1.110",
    modelName: "Lenovo ThinkSystem SR650",
    location: "DC-SEL / RACK-A02 / 20U",
    manufacturer: "Lenovo",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 20,
    positionType: "FRONT",
    serialNumber: "LENO-SN-9009",
    os: "RHEL 8",
    cpuSpec: "Intel Xeon Gold 5218 @ 2.3GHz 2CPU",
    memorySpec: "512GB (16x 32GB) DDR4",
    diskSpec: "2TB NVMe SSD x 4",
    macAddress: "00:1A:2B:3C:4D:09",
    managerId: "devops_team",
    installationDate: "2023-08-01",
    notes: "Kubernetes Worker Node 01.",
    monitoringEnabled: true,
    cpuThresholdWarning: 85,
    cpuThresholdCritical: 95,
    memoryThresholdWarning: 85,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 80,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 10. Supermicro Server (DISPOSED, Unassigned) ---
  {
    id: "10",
    equipmentName: "Old-Backup-Server",
    status: "DISPOSED",
    ipAddress: null,
    modelName: "Supermicro SuperServer 5018D",
    location: "폐기됨",
    manufacturer: "Supermicro",
    equipmentType: "SERVER",
    unitSize: 1,
    datacenterId: null,
    rackId: null,
    startUnit: null,
    positionType: null,
    serialNumber: "SM-SN-1010",
    os: null,
    cpuSpec: "Intel Xeon D-1541",
    memorySpec: "32GB DDR4",
    diskSpec: "1TB SATA HDD x 2",
    macAddress: null,
    managerId: "sys_admin",
    installationDate: "2018-05-15",
    notes: "Disposed on 2023-10-01.",
    monitoringEnabled: false,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: 70,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 11. Arista Switch (NORMAL, dc1/rack1) ---
  {
    id: "11",
    equipmentName: "Switch-Leaf-A01",
    status: "NORMAL",
    ipAddress: "192.168.1.10",
    modelName: "Arista 7050SX-64",
    location: "DC-SEL / RACK-A01 / 39U",
    manufacturer: "Arista",
    equipmentType: "SWITCH",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack1",
    startUnit: 39,
    positionType: "FRONT",
    serialNumber: "ARI-SN-1111",
    os: "EOS",
    cpuSpec: "N/A",
    memorySpec: "4GB",
    diskSpec: "4GB Flash",
    macAddress: "00:1A:2B:3C:4D:11",
    managerId: "net_admin",
    installationDate: "2023-01-05",
    notes: "Leaf switch for Rack A01.",
    monitoringEnabled: true,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 12. Dell Server (NORMAL, dc2/rack3) ---
  {
    id: "12",
    equipmentName: "Analytics-Server-01",
    status: "NORMAL",
    ipAddress: "10.0.1.101",
    modelName: "Dell PowerEdge R750",
    location: "DC-BUS / RACK-B01 / 10U",
    manufacturer: "Dell",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 10,
    positionType: "FRONT",
    serialNumber: "DELL-SN-1212",
    os: "RHEL 8",
    cpuSpec: "Intel Xeon Gold 6338 @ 2.0GHz 2CPU",
    memorySpec: "1TB (16x 64GB) DDR4",
    diskSpec: "4TB NVMe SSD x 8",
    macAddress: "00:1A:2B:3C:4D:12",
    managerId: "data_team",
    installationDate: "2023-09-15",
    notes: "BigData Analytics server.",
    monitoringEnabled: true,
    cpuThresholdWarning: 90,
    cpuThresholdCritical: 98,
    memoryThresholdWarning: 90,
    memoryThresholdCritical: 98,
    diskThresholdWarning: 85,
    diskThresholdCritical: 95,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 13. HP Server (NORMAL, dc1/rack1) ---
  {
    id: "13",
    equipmentName: "Web-Server-01",
    status: "NORMAL",
    ipAddress: "192.168.1.100",
    modelName: "HP ProLiant DL360 Gen10",
    location: "DC-SEL / RACK-A01 / 20U",
    manufacturer: "HP",
    equipmentType: "SERVER",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack1",
    startUnit: 20,
    positionType: "FRONT",
    serialNumber: "HP-SN-1313",
    os: "Ubuntu 22.04 LTS",
    cpuSpec: "Intel Xeon Silver 4214 @ 2.2GHz 2CPU",
    memorySpec: "128GB (4x 32GB) DDR4",
    diskSpec: "1TB NVMe SSD x 2",
    macAddress: "00:1A:2B:3C:4D:13",
    managerId: "admin_lee",
    installationDate: "2023-03-15",
    notes: "Web server cluster node 1.",
    monitoringEnabled: true,
    cpuThresholdWarning: 75,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 75,
    memoryThresholdCritical: 90,
    diskThresholdWarning: 80,
    diskThresholdCritical: 95,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 14. APC PDU (NORMAL, dc2/rack3) ---
  {
    id: "14",
    equipmentName: "PDU-B01-R",
    status: "NORMAL",
    ipAddress: "10.0.1.251",
    modelName: "APC AP8861",
    location: "DC-BUS / RACK-B01 / 1U",
    manufacturer: "APC",
    equipmentType: "PDU",
    unitSize: 1, // (0U PDU도 있지만, 1U로 가정)
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 1,
    positionType: "REAR",
    serialNumber: "APC-SN-1414",
    os: null,
    cpuSpec: null,
    memorySpec: null,
    diskSpec: null,
    macAddress: "00:1A:2B:3C:4D:14",
    managerId: "infra_team",
    installationDate: "2022-11-20",
    notes: "Rack B01 Right PDU.",
    monitoringEnabled: false,
    cpuThresholdWarning: null,
    cpuThresholdCritical: null,
    memoryThresholdWarning: null,
    memoryThresholdCritical: null,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 15. Lenovo Server (INACTIVE, Unassigned) ---
  {
    id: "15",
    equipmentName: "K8S-Worker-Spare-01",
    status: "INACTIVE",
    ipAddress: null,
    modelName: "Lenovo ThinkSystem SR650",
    location: "미지정 (재고)",
    manufacturer: "Lenovo",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: null,
    rackId: null,
    startUnit: null,
    positionType: null,
    serialNumber: "LENO-SN-1515",
    os: null,
    cpuSpec: "Intel Xeon Gold 5218 @ 2.3GHz 2CPU",
    memorySpec: "512GB (16x 32GB) DDR4",
    diskSpec: "2TB NVMe SSD x 4",
    macAddress: null,
    managerId: "devops_team",
    installationDate: null,
    notes: "Spare node for K8S cluster.",
    monitoringEnabled: false,
    cpuThresholdWarning: 85,
    cpuThresholdCritical: 95,
    memoryThresholdWarning: 85,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 80,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 16. Cisco Router (MAINTENANCE, dc2/rack3) ---
  {
    id: "16",
    equipmentName: "Router-Edge-02",
    status: "MAINTENANCE",
    ipAddress: "10.0.1.253",
    modelName: "Cisco ISR 4331",
    location: "DC-BUS / RACK-B01 / 40U",
    manufacturer: "Cisco",
    equipmentType: "ROUTER",
    unitSize: 2,
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 38, // 2U 크기 (38, 39)
    positionType: "FRONT",
    serialNumber: "CSCO-SN-1616",
    os: "IOS-XE",
    cpuSpec: "N/A",
    memorySpec: "4GB",
    diskSpec: "8GB Flash",
    macAddress: "00:1A:2B:3C:4D:16",
    managerId: "net_admin",
    installationDate: "2022-11-20",
    notes: "Busan DC Edge Router 2. FW upgrade pending.",
    monitoringEnabled: true,
    cpuThresholdWarning: 60,
    cpuThresholdCritical: 80,
    memoryThresholdWarning: 60,
    memoryThresholdCritical: 80,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 17. Dell Server (NORMAL, dc1/rack2) ---
  {
    id: "17",
    equipmentName: "VM-Host-01",
    status: "NORMAL",
    ipAddress: "192.168.1.120",
    modelName: "Dell PowerEdge R640",
    location: "DC-SEL / RACK-A02 / 30U",
    manufacturer: "Dell",
    equipmentType: "SERVER",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 30,
    positionType: "FRONT",
    serialNumber: "DELL-SN-1717",
    os: "VMware ESXi 7.0",
    cpuSpec: "Intel Xeon Gold 6248 @ 2.5GHz 2CPU",
    memorySpec: "768GB (12x 64GB) DDR4",
    diskSpec: "1TB SSD x 2 (Boot), 4TB NVMe x 4 (Datastore)",
    macAddress: "00:1A:2B:3C:4D:17",
    managerId: "sys_admin",
    installationDate: "2023-02-25",
    notes: "Virtualization Host 01.",
    monitoringEnabled: true,
    cpuThresholdWarning: 80,
    cpuThresholdCritical: 95,
    memoryThresholdWarning: 85,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 70,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 18. HP Server (NORMAL, dc1/rack2) ---
  {
    id: "18",
    equipmentName: "VM-Host-02",
    status: "NORMAL",
    ipAddress: "192.168.1.121",
    modelName: "HP ProLiant DL360 Gen10",
    location: "DC-SEL / RACK-A02 / 31U",
    manufacturer: "HP",
    equipmentType: "SERVER",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 31,
    positionType: "FRONT",
    serialNumber: "HP-SN-1818",
    os: "VMware ESXi 7.0",
    cpuSpec: "Intel Xeon Gold 6248 @ 2.5GHz 2CPU",
    memorySpec: "768GB (12x 64GB) DDR4",
    diskSpec: "1TB SSD x 2 (Boot), 4TB NVMe x 4 (Datastore)",
    macAddress: "00:1A:2B:3C:4D:18",
    managerId: "sys_admin",
    installationDate: "2023-02-25",
    notes: "Virtualization Host 02.",
    monitoringEnabled: true,
    cpuThresholdWarning: 80,
    cpuThresholdCritical: 95,
    memoryThresholdWarning: 85,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 70,
    diskThresholdCritical: 90,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 19. Juniper Switch (NORMAL, dc1/rack2) ---
  {
    id: "19",
    equipmentName: "Switch-Leaf-A02",
    status: "NORMAL",
    ipAddress: "192.168.1.11",
    modelName: "Juniper QFX5100",
    location: "DC-SEL / RACK-A02 / 39U",
    manufacturer: "Juniper",
    equipmentType: "SWITCH",
    unitSize: 1,
    datacenterId: "dc1",
    rackId: "rack2",
    startUnit: 39,
    positionType: "FRONT",
    serialNumber: "JNPR-SN-1919",
    os: "Junos",
    cpuSpec: "N/A",
    memorySpec: "8GB",
    diskSpec: "32GB SSD",
    macAddress: "00:1A:2B:3C:4D:19",
    managerId: "net_admin",
    installationDate: "2023-01-05",
    notes: "Leaf switch for Rack A02.",
    monitoringEnabled: true,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 70,
    memoryThresholdCritical: 90,
    diskThresholdWarning: null,
    diskThresholdCritical: null,
    imageUrlFront: null,
    imageUrlRear: null,
  },
  // --- 20. Dell Server (NORMAL, dc2/rack3) ---
  {
    id: "20",
    equipmentName: "Logging-Server-01",
    status: "NORMAL",
    ipAddress: "10.0.1.102",
    modelName: "Dell PowerEdge R540",
    location: "DC-BUS / RACK-B01 / 20U",
    manufacturer: "Dell",
    equipmentType: "SERVER",
    unitSize: 2,
    datacenterId: "dc2",
    rackId: "rack3",
    startUnit: 20,
    positionType: "FRONT",
    serialNumber: "DELL-SN-2020",
    os: "Ubuntu 20.04 LTS",
    cpuSpec: "Intel Xeon Silver 4208 @ 2.1GHz 2CPU",
    memorySpec: "128GB (8x 16GB) DDR4",
    diskSpec: "512GB SSD (OS), 10TB HDD x 8 (Logs)",
    macAddress: "00:1A:2B:3C:4D:20",
    managerId: "devops_team",
    installationDate: "2022-12-10",
    notes: "Central logging server (ELK Stack).",
    monitoringEnabled: true,
    cpuThresholdWarning: 70,
    cpuThresholdCritical: 90,
    memoryThresholdWarning: 80,
    memoryThresholdCritical: 95,
    diskThresholdWarning: 90,
    diskThresholdCritical: 98,
    imageUrlFront: null,
    imageUrlRear: null,
  },
];