// import type { ServerRoom } from "../types";

// export const MOCK_SERVER_ROOMS: ServerRoom[] = [
//   {
//     id: "a1",
//     name: "IDC A-Zone, Floor 3",
//     code: "IDC-A3",
//     description: "Primary data center in Seoul",
//     location: "Seoul, South Korea",
//     rackCount: 32,
//     status: "Normal",
//   },
//   {
//     id: "b2",
//     name: "IDC B-Zone, Floor 2",
//     code: "IDC-B2",
//     description: "Secondary data center in Tokyo",
//     location: "Tokyo, Japan",
//     rackCount: 24,
//     status: "Warning",
//   },
//   {
//     id: "c3",
//     name: "IDC C-Zone, Floor 1",
//     code: "IDC-C1",
//     description: "Regional hub in Singapore",
//     location: "Singapore",
//     rackCount: 48,
//     status: "Normal",
//   },
//   {
//     id: "d4",
//     name: "IDC D-Zone, Floor 4",
//     code: "IDC-D4",
//     description: "Backup facility in Hong Kong",
//     location: "Hong Kong",
//     rackCount: 16,
//     status: "Critical",
//   },
//   {
//     id: "e5",
//     name: "IDC E-Zone, Floor 5",
//     code: "IDC-E5",
//     description: "Expansion site in Mumbai",
//     location: "Mumbai, India",
//     rackCount: 28,
//     status: "Normal",
//   },
//   {
//     id: "f6",
//     name: "IDC F-Zone, Floor 6",
//     code: "IDC-F6",
//     description: "Regional center in Sydney",
//     location: "Sydney, Australia",
//     rackCount: 20,
//     status: "Maintenance",
//   },
// ];
